import { scanCodeWithGemini } from "./geminiScanner.js";
import { virtualPatchEngine } from "./virtualPatchEngine.js";
import { jailService } from "./jailService.js";
import { notifyBreach } from "./notifier.js";
import { config } from "../config.js";

/**
 * FORTRESS ASYNCHRONOUS AI AUDIT QUEUE (Out-of-Band Deep Cognitive Worker)
 * Solves AppSec critique: Synchronous WAN Latency & External LLM Bottlenecks in Request Loop.
 *
 * Capabilities:
 * 1. Zero Latency for End-Users: HTTP responses are served immediately (<1ms) by Edge/In-Memory tiers.
 * 2. Asynchronous Deep Cognitive Analysis: Google Gemini 2.0 Flash audits complex payloads out-of-band.
 * 3. Autonomous Immune Reflex: If Gemini uncovers a zero-day or business logic exploit, the worker
 *    synthesizes a runtime virtual hotpatch, auto-jails the attacker IP, and notifies the SecOps team.
 */
class AiAuditQueue {
  constructor() {
    this.queue = [];
    this.isProcessing = false;
    this.maxQueueSize = 500;
    this.totalAudited = 0;
    this.totalZeroDaysCaught = 0;
    this.recentAuditResults = [];
    this.maxRecentResults = 50;
  }

  /**
   * Enqueue a request for asynchronous deep cognitive auditing
   */
  enqueue(item) {
    if (!config.geminiApiKey) return false;
    if (this.queue.length >= this.maxQueueSize) {
      this.queue.shift(); // Evict oldest to protect memory
    }

    this.queue.push({
      ...item,
      enqueuedAt: Date.now(),
    });

    // Kick off worker if idle
    if (!this.isProcessing) {
      this.processNext();
    }
    return true;
  }

  async processNext() {
    if (this.queue.length === 0) {
      this.isProcessing = false;
      return;
    }

    this.isProcessing = true;
    const task = this.queue.shift();

    try {
      const { path = "/", method = "POST", headers = {}, body = null, clientIp = "unknown", siteCategory = "STANDARD_API" } = task;

      const aiResult = await scanCodeWithGemini({
        code: JSON.stringify({ method, path, headers, body, context: siteCategory }, null, 2),
        filename: `async_req_${method}_${path.replace(/[^a-zA-Z0-9]/g, "_")}`,
        type: "http_request_payload",
      });

      this.totalAudited += 1;

      if (aiResult.fortress_status === "BREACHED") {
        this.totalZeroDaysCaught += 1;
        console.warn(`🚨 [OOB AI WORKER INTERCEPT] Gemini discovered zero-day in background: ${aiResult.verdict}`);

        // 1. Autonomous Immune Reflex: Deploy In-Memory Virtual Hotpatch
        try {
          const patchId = "VP-OOB-" + Date.now().toString(36).toUpperCase();
          virtualPatchEngine.applyPatch({
            id: patchId,
            name: `Autonomous Immune Hotpatch: ${path.slice(0, 32)}`,
            path: `^${path.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`,
            method: method || "ALL",
            cwe: aiResult.findings?.[0]?.cwe || "CWE-ZERO-DAY",
            description: `Auto-generated by Gemini 2.0 Flash async worker for: ${aiResult.verdict}`,
            rules: [
              {
                field: "body.*",
                op: "DISALLOW_SYNTAX",
                pattern: "DISALLOW_SYNTAX",
                message: `Blocked by autonomous out-of-band hotpatch ${patchId}`,
              },
            ],
          });
        } catch {}

        // 2. Auto-jail the attacker IP
        jailService.banIp(clientIp, `OOB Gemini Zero-Day Intercept: ${aiResult.verdict}`, "LAYER 3: ASYNC_AI_WORKER", 48 * 3600 * 1000);
        jailService.recordEvent({
          ip: clientIp,
          wall: "LAYER 3: ASYNC_AI_WORKER",
          threat_level: aiResult.threat_level || "CRITICAL",
          reason: `Background cognitive analysis flagged zero-day exploit: ${aiResult.verdict}`,
          action: "BAN_IP_24H",
          path,
          evidence: aiResult.findings?.[0]?.issue || "Zero-Day exploit detected asynchronously",
        });

        // 3. Dispatch Live Emergency Alerts (Telegram/Slack/Discord)
        notifyBreach(aiResult, { filename: `${method} ${path} (OOB Background Audit)` });
      }

      // Record telemetry
      this.recentAuditResults.unshift({
        id: "audit_" + Math.random().toString(36).slice(2, 9),
        path: task.path,
        method: task.method,
        clientIp: task.clientIp,
        status: aiResult.fortress_status,
        verdict: aiResult.verdict,
        score: aiResult.score,
        completedAt: new Date().toISOString(),
      });
      if (this.recentAuditResults.length > this.maxRecentResults) {
        this.recentAuditResults.pop();
      }
    } catch (err) {
      console.warn("Async AI Audit Worker error:", err.message);
    }

    // Rate-limit pacing: 250ms delay between Gemini API calls
    setTimeout(() => this.processNext(), 250);
  }

  getStats() {
    return {
      queueLength: this.queue.length,
      isProcessing: this.isProcessing,
      totalAudited: this.totalAudited,
      totalZeroDaysCaught: this.totalZeroDaysCaught,
      recentAudits: this.recentAuditResults.slice(0, 10),
    };
  }
}

export const aiAuditQueue = new AiAuditQueue();
